[project]
name = "flet-mobile-template"
version = "0.1.0"
description = "Template for building mobile apps with Flet"
requires-python = ">=3.10"
readme = "README.md"

dependencies = [
    "flet>=0.26,<1.0"
]

[project.optional-dependencies]

dev = [
    "black",
    "ruff",
    "pytest",
]

api = [
    "requests",
    "httpx",
    "pydantic",
]

database = [
    "aiosqlite"
]

mobile = [
    "requests",
    "aiosqlite"
]

[tool.flet]
org = "com.example"
product = "FletTemplate"
company = "Example"
build_number = 1

[tool.flet.app]
path = "."

[tool.flet.android]
icon = "assets/icon.png"

[tool.flet.splash]
image = "assets/splash.png"
background_color = "#ffffff"

[tool.flet.flutter]
dependencies = []
